[package]
name = "yahoo-finance-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
log = "0.4"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
reqwest = {version = "0.12", features = ["blocking", "cookies"] }
